### ISSUE TITLE
Operator Mono version

### ISSUE THREAD

**Issue by carlosriveroib** [uloco/theme-bluloco-dark#1]
Hi!! I Love your theme, is the best for me.
Could you make a version with Operator Mono font?
![operator mono](https://user-images.githubusercontent.com/9528363/34979386-72b477e0-faa1-11e7-976d-34b860548ea8.png)

It will be great!
Thanks a lot!

**Comment by uloco** [comment]
Hi, thanks for your support.
It is really refreshing to hear :)

Normally you can change the font by yourself in the user settings. 
Which editor are you using? VSCode ?
If this is true, just set the property `editor.fontFamily` to the font name you like.
Make sure you have installed the font on your machine.

**Comment by carlosriveroib** [comment]
Yes, I'm using VSCode.
I know that I can change the font. I made that screenshot with this theme. 
https://github.com/chiragpat/tomorrow-and-tomorrow-night-operator-mono-theme/blob/master/themes/Tomorrow_Night_Eighties_OperatorMono.tmTheme
Search for fontStyle, check keywords like "import", "from", "if", "else", comments... are using italic.

If I switch to your theme and setting Operator Mono font it seems like this.
![bluloco](https://user-images.githubusercontent.com/9528363/34980050-821155a8-faa3-11e7-897f-85e1811f8879.png)

Don't worry. If you wish I can try and make you a PR with Operator Mono Version of your theme

**Comment by uloco** [comment]
Hm I don't really understand, what the font has to do with the italics.
This is defined in the theme, not in the font.
I don't like italics in my code, because they are not so easy to spot.
Different colors work better for me.

**Comment by uloco** [comment]
It is hard enough for me, to maintain two different variants light and dark, so i don't have time to maintain another variant. If you want to add italics, feel free to fork this project :)

**Comment by carlosriveroib** [comment]
Ok, I will try.
Thank you a lot!

**Comment by uloco** [comment]
Hey there! I had time to look into this italics version. Since VSCode gives us a lot more possibilities in writing extensions at the moment, I pushed a Italic variant of the original Bluloco Theme to the marketplace recently. If you want, you can try using it. If you have the bluloco theme installed, just use the _Bluloco Dark Italic_ variant when choosing themes. I hope this fulfills your needs.
The drawback of maintaining an own variant (as you do right now) is, that you don't get all the good updates into your extension I did recently.
The light variant will follow soon. Please send me some feedback, if you like how it looks right now.

**Comment by carlosriveroib** [comment]
Hi, sorry for late reply. I've been testing the Italic version. It's very good but in my opinion I would change some things. I will try to explain them about some screenshots but it's just my opinion. I think there are too much italic things.

![captura de pantalla 2018-08-01 a las 10 47 25](https://user-images.githubusercontent.com/9528363/43511722-6765a652-9579-11e8-8c05-2f769e803902.png)
Here isn't necessary

![captura de pantalla 2018-08-01 a las 10 47 40](https://user-images.githubusercontent.com/9528363/43511787-9f86c598-9579-11e8-8bdf-4936b11daf9b.png)
Too much brown here and unnecessary italic

![captura de pantalla 2018-08-01 a las 10 47 53](https://user-images.githubusercontent.com/9528363/43511844-c28d230c-9579-11e8-98e4-f537e1220726.png)
Same here.

![captura de pantalla 2018-08-01 a las 10 48 08](https://user-images.githubusercontent.com/9528363/43511872-d523511c-9579-11e8-89ce-5f1eba36053c.png)

![captura de pantalla 2018-08-01 a las 10 48 43](https://user-images.githubusercontent.com/9528363/43511916-fa2fd9b2-9579-11e8-803f-4d7426fc62ed.png)
I would not use here italic, "limit" and "offset" should be brown because they are using ES6 shorthands.

How I said before, I really appreciate your work and this is just my opinion.

**Comment by uloco** [comment]
So you would want the keywords to be italic (including `this`) but all object properties should not be italic, right? I still want to color Object properties brown, because they belong to something. Local variables / primitives are colorless/white. This has nothing to do with the italics version in general.
I will look into this, when I got time. Would you mind deleting your extension from the marketplace? If you want further color adjustments etc, you can just override mine in your own user preferences. So you will keep on being up to date and can adjust it however you want it to be?

**Comment by uloco** [comment]
Is there a theme I can use for reference purposes?

**Comment by carlosriveroib** [comment]
Sorry for my late answer, I was on holidays.

> So you would want the keywords to be italic (including this) but all object properties should not be italic, right?

Exactly, that's the only change I want. 

> I still want to color Object properties brown, because they belong to something. Local variables / primitives are colorless/white

Ok, I agree.

> Would you mind deleting your extension from the marketplace?

Yes sure, this is your theme. I just wanted italic and you did.

Your theme doesn't list here https://vscodethemes.com/
In their git repo they explain what you must do to list your theme, just if you want. 

Thank you very much.

**Comment by uloco** [comment]
Until I got time to update the theme, you can simply adjust it in your own user settings:
Add for both themes respectively:
```
  "editor.tokenColorCustomizations": {
    "[Bluloco Dark Italic]": {
      "textMateRules": [
        {
          "scope": [
            "variable.other.object.property",
            "variable.other.property",
            "variable.object.property",
            "support.variable.property",
            "meta.object-literal.key"
          ],
          "settings": {
            "fontStyle": ""
          }
        }
      ]
    }
  }
```

**Comment by carlosriveroib** [comment]
Thank you, that's what I want.

**Comment by uloco** [comment]
@carlosriveroib Please remove your operator mono variant from vsce as you promised. The issues is now resolved and released.

**Comment by carlosriveroib** [comment]
Done. Thanks for all!
