### ISSUE TITLE
The warnings of the current active file are not clear enough

### ISSUE THREAD

**Issue by qipengh** [uloco/theme-bluloco-dark#14]
beautiful theme. but when black theme, file name not clear.

![image](https://user-images.githubusercontent.com/25411141/144044072-5244ff79-8b1a-4941-bbb1-9d8263c691e2.png)

when use light theme, its very clear
![image](https://user-images.githubusercontent.com/25411141/144044163-1b15d718-ce70-4c8b-afa3-53108d74896a.png)

could you help me fix it? thanks

**Comment by qipengh** [comment]
It’s hard to see that I’m currently working on this file
![image](https://user-images.githubusercontent.com/25411141/144044496-647b5ead-242f-4c1f-9337-aaebbcf841c4.png)

**Comment by qipengh** [comment]
i find it，thinks

set
```  
"workbench.colorCustomizations": {
        "tab.activeBackground": "#5f80629a"
```

**Comment by uloco** [comment]
You could also use the setting `"window.titleBarStyle": "custom",`. There is a blue line on the top border of the active tab, which is just not visible because your window title is light.
