### ISSUE TITLE
Terminal colors changed

### ISSUE THREAD

**Issue by jonaslreiter** [uloco/theme-bluloco-dark#15]
What's the reason behind commit 78f8b38e4a602b48b3eadf935dafdba37ea4322c?

I see that most colors changed ever so slightly but `terminal.ansiBlack` has been removed completely, causing it to be rendered as `#000000` in VS Code.

I was using the brighter-than-pitch-black black for autosuggestions in my terminal and this suddenly became much less readable for me:
<img width="311" alt="before" src="https://user-images.githubusercontent.com/58821240/210315662-7943c655-31e7-4b49-8810-1b66639681a6.png">
<img width="311" alt="after" src="https://user-images.githubusercontent.com/58821240/210315657-8fbaa997-88a9-42d8-b293-00f7635a0355.png">

**Comment by uloco** [comment]
Looks like I removed the black one by mistake, my bad. Thanks for reporting!

**Comment by uloco** [comment]
The terminal colors were wrong and not the original colors of bluloco. I was working on the neovim port and realized this so fixed it. And by mistake I removed black 😅

**Comment by uloco** [comment]
I just released a new version. It should be available anytime soon. Have a great day!

**Comment by jonaslreiter** [comment]
Great, I updated already. Thanks a lot!
