### ISSUE TITLE
How to change the color of terminal path font?

### ISSUE THREAD

**Issue by chaneesong** [uloco/theme-bluloco-dark#17]
I like your theme. But I have a question. Path font is white in term2 but black in vscode. Is there any way to change path font to white in vscode?

in vscode,
![Screenshot 2023-02-17 at 12 33 19 AM](https://user-images.githubusercontent.com/73852281/219414581-a7a98b98-1d0e-4564-bc52-f79a627a99d7.png)

in iterm2,
![Screenshot 2023-02-17 at 12 33 30 AM](https://user-images.githubusercontent.com/73852281/219414661-67e40998-de6a-4d96-b8c6-6ba305ff26b4.png)

**Comment by uloco** [comment]
It is not black for me in vscode. Which prompt are you using? I am on powerlevel10k and it works the same in iTerm and VSCode.

**Comment by chaneesong** [comment]
I also use powerlevel10k and iTerm2.

![Screenshot 2023-02-17 at 6 58 15 PM](https://user-images.githubusercontent.com/73852281/219612943-78e0ac3f-b7b0-479f-9167-c91c41af198f.png)

Do I have to support 256 colors or true colors in vscode?

**Comment by uloco** [comment]
> Do I have to support 256 colors or true colors in vscode?

I don't know what you mean, is there a setting for this in vscode? I think I did not change anything specific to this.

**Comment by chaneesong** [comment]
I see. Maybe my iTerm or vscode has a wrong setting.
I thought the two colors were meant to be different.

**Comment by uloco** [comment]
Oh I think I had to set this   `"terminal.integrated.minimumContrastRatio": 1`, to make the colors work. VSCode changed the behavior at some point. Can you try this

**Comment by chaneesong** [comment]
Wow! It's working properly! Thank you so much!!
