### ISSUE TITLE
Suggestion: More readable comments (more contrast)

### ISSUE THREAD

**Issue by jovid78** [uloco/theme-bluloco-dark#18]
I absolutely love Bluloco Dark (+ italics).

I have not changed my theme in years (which means a lot... I used to change it very frequently).

The one thing I would suggest is to make the comments in dark mode be a bit more readable (have a bit more contrast).

While I do appreciate them being 'greyed out'  , I find myself sometimes making more of an effort to read them.

Thanks again for the theme!

**Comment by uloco** [comment]
Hey there, thanks :) 
You can totally change the color for yourself in your settings, specific to your used theme. Let me know if you need help doing so. Not on my laptop rn.

**Comment by uloco** [comment]
Is there anything I can help you with, did you manage to do it on your own? I'm closing this now, please reach out when you need further help.
