### ISSUE TITLE
How to edit statusbar color?

### ISSUE THREAD

**Issue by IdanAdar** [uloco/theme-bluloco-dark#5]
Hi,

I'd like to modify the color of the status bar while keep using this theme.
Is it possible to do this in settings.json?

**Comment by uloco** [comment]
Hey. This can be done with the following configuration:

```
  "workbench.colorCustomizations": { "[Bluloco Dark]": {"statusBar.background": "#ff0000"}},
```

**Comment by IdanAdar** [comment]
Thanks!

**Comment by uloco** [comment]
@IdanAdar I have changed the default statusbar color to a less distracting one. Give it a try. The color of the border now indicates the different types (file, folder, debug).
See a preview in the screenshots.
