### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by IdanAdar** [uloco/theme-bluloco-dark#7]
Please clarify what is the license for this extension.

**Comment by uloco** [comment]
Added LICENSE (LGPL-3.0), see 505f66e27010d5ecd748b58d6b2379054709b258

**Comment by uloco** [comment]
May I ask you, what you want to do with the code?
Perhaps there is a way to keep it in the original repository? ;)

**Comment by IdanAdar** [comment]
Nothing. My company requires either MIT or GPL for using extensions.

**Comment by uloco** [comment]
Is `LGPL-3.0` a problem?
Because if GPL is cool with your company, LGPL should also be ...
